version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
  web:
    build: .
    command:  bash -c "python manage.py makemigrations && 
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000 "
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=bewise.settings
    volumes:
      - .:/usr/src/bewise/
    env_file:
      - ./.env
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    container_name: demo-pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always

volumes:
  db:
    driver: local
